name = "todo-preview-prod"
main = "src/index.js"
account_id = "73bb2ac2fe4425ad273eab14819a5f22"
compatibility_date = "2025-06-08" 


[[kv_namespaces]]
binding = "TODOS"
id = "2bc159f09a604c0eaffdadc6f2b9c0d0"
