name = "todo-preview-prod"
main = "src/index.js"
account_id = "73bb2ac2fe4425ad273eab14819a5f22"
compatibility_date = "2025-06-08" 


[[kv_namespaces]]
binding = "TODOS"
id = "f7592a403bbd4eb3a88651e6425cb55b"

[env.dev]
name = "todo-preview-dev"


[[env.dev.kv_namespaces]]
binding = "TODOS"
id = "7ea83e2cfa3a4a5e88b8301a1375c9c0"
